// themeAssets.gen.ts — GENERATED by mobile/scripts/sync-theme-assets.mjs.
//
// Do not edit by hand: run `npm run mobile:assets` to regenerate. One literal
// `require()` per bundled theme PNG (Metro resolves static requires only), with
// the pixel size measured from each PNG's IHDR header. Keyed
// `<theme-name>/<file>` — the exact lookup `resolveAsset` performs.

import type { ImageSourcePropType } from 'react-native';

export interface ThemeAssetSource {
  /** The bundled image module Metro resolves from the literal require. */
  source: ImageSourcePropType;
  /** Pixel width measured from the PNG's IHDR header. */
  width: number;
  /** Pixel height measured from the PNG's IHDR header. */
  height: number;
}

export const THEME_ASSETS: Record<string, ThemeAssetSource> = {
  'fantasy/boss-grunt-attack.png': {
    source: require('../assets/themes/fantasy/boss-grunt-attack.png'),
    width: 96,
    height: 96,
  },
  'fantasy/boss-grunt-death.png': {
    source: require('../assets/themes/fantasy/boss-grunt-death.png'),
    width: 96,
    height: 96,
  },
  'fantasy/boss-grunt-hurt.png': {
    source: require('../assets/themes/fantasy/boss-grunt-hurt.png'),
    width: 96,
    height: 96,
  },
  'fantasy/boss-grunt-idle.png': {
    source: require('../assets/themes/fantasy/boss-grunt-idle.png'),
    width: 96,
    height: 96,
  },
  'fantasy/enemy-grunt-attack.png': {
    source: require('../assets/themes/fantasy/enemy-grunt-attack.png'),
    width: 64,
    height: 64,
  },
  'fantasy/enemy-grunt-death.png': {
    source: require('../assets/themes/fantasy/enemy-grunt-death.png'),
    width: 64,
    height: 64,
  },
  'fantasy/enemy-grunt-hurt.png': {
    source: require('../assets/themes/fantasy/enemy-grunt-hurt.png'),
    width: 64,
    height: 64,
  },
  'fantasy/enemy-grunt-idle.png': {
    source: require('../assets/themes/fantasy/enemy-grunt-idle.png'),
    width: 64,
    height: 64,
  },
  'fantasy/gear-necklace-t1.png': {
    source: require('../assets/themes/fantasy/gear-necklace-t1.png'),
    width: 48,
    height: 48,
  },
  'fantasy/gear-necklace-t2.png': {
    source: require('../assets/themes/fantasy/gear-necklace-t2.png'),
    width: 48,
    height: 48,
  },
  'fantasy/gear-necklace-t3.png': {
    source: require('../assets/themes/fantasy/gear-necklace-t3.png'),
    width: 48,
    height: 48,
  },
  'fantasy/gear-necklace-t4.png': {
    source: require('../assets/themes/fantasy/gear-necklace-t4.png'),
    width: 48,
    height: 48,
  },
  'fantasy/gear-ring1-t1.png': {
    source: require('../assets/themes/fantasy/gear-ring1-t1.png'),
    width: 48,
    height: 48,
  },
  'fantasy/gear-ring1-t2.png': {
    source: require('../assets/themes/fantasy/gear-ring1-t2.png'),
    width: 48,
    height: 48,
  },
  'fantasy/gear-ring1-t3.png': {
    source: require('../assets/themes/fantasy/gear-ring1-t3.png'),
    width: 48,
    height: 48,
  },
  'fantasy/gear-ring1-t4.png': {
    source: require('../assets/themes/fantasy/gear-ring1-t4.png'),
    width: 48,
    height: 48,
  },
  'fantasy/gear-ring2-t1.png': {
    source: require('../assets/themes/fantasy/gear-ring2-t1.png'),
    width: 48,
    height: 48,
  },
  'fantasy/gear-ring2-t2.png': {
    source: require('../assets/themes/fantasy/gear-ring2-t2.png'),
    width: 48,
    height: 48,
  },
  'fantasy/gear-ring2-t3.png': {
    source: require('../assets/themes/fantasy/gear-ring2-t3.png'),
    width: 48,
    height: 48,
  },
  'fantasy/gear-ring2-t4.png': {
    source: require('../assets/themes/fantasy/gear-ring2-t4.png'),
    width: 48,
    height: 48,
  },
  'fantasy/gear-weapon-t1.png': {
    source: require('../assets/themes/fantasy/gear-weapon-t1.png'),
    width: 48,
    height: 48,
  },
  'fantasy/gear-weapon-t2.png': {
    source: require('../assets/themes/fantasy/gear-weapon-t2.png'),
    width: 48,
    height: 48,
  },
  'fantasy/gear-weapon-t3.png': {
    source: require('../assets/themes/fantasy/gear-weapon-t3.png'),
    width: 48,
    height: 48,
  },
  'fantasy/gear-weapon-t4.png': {
    source: require('../assets/themes/fantasy/gear-weapon-t4.png'),
    width: 48,
    height: 48,
  },
  'fantasy/player-attack.png': {
    source: require('../assets/themes/fantasy/player-attack.png'),
    width: 64,
    height: 64,
  },
  'fantasy/player-hurt.png': {
    source: require('../assets/themes/fantasy/player-hurt.png'),
    width: 64,
    height: 64,
  },
  'fantasy/player-idle.png': {
    source: require('../assets/themes/fantasy/player-idle.png'),
    width: 64,
    height: 64,
  },
  'fantasy/shiny-cache.png': {
    source: require('../assets/themes/fantasy/shiny-cache.png'),
    width: 48,
    height: 48,
  },
  'fantasy/shiny-drop.png': {
    source: require('../assets/themes/fantasy/shiny-drop.png'),
    width: 48,
    height: 48,
  },
  'fantasy/shiny-frenzy.png': {
    source: require('../assets/themes/fantasy/shiny-frenzy.png'),
    width: 48,
    height: 48,
  },
  'fantasy/shiny-idle.png': {
    source: require('../assets/themes/fantasy/shiny-idle.png'),
    width: 48,
    height: 48,
  },
  'fantasy/spawn-popup.png': {
    source: require('../assets/themes/fantasy/spawn-popup.png'),
    width: 96,
    height: 32,
  },
  'lucky/boss-grunt-attack.png': {
    source: require('../assets/themes/lucky/boss-grunt-attack.png'),
    width: 96,
    height: 96,
  },
  'lucky/boss-grunt-death.png': {
    source: require('../assets/themes/lucky/boss-grunt-death.png'),
    width: 96,
    height: 96,
  },
  'lucky/boss-grunt-hurt.png': {
    source: require('../assets/themes/lucky/boss-grunt-hurt.png'),
    width: 96,
    height: 96,
  },
  'lucky/boss-grunt-idle.png': {
    source: require('../assets/themes/lucky/boss-grunt-idle.png'),
    width: 96,
    height: 96,
  },
  'lucky/enemy-grunt-attack.png': {
    source: require('../assets/themes/lucky/enemy-grunt-attack.png'),
    width: 64,
    height: 64,
  },
  'lucky/enemy-grunt-death.png': {
    source: require('../assets/themes/lucky/enemy-grunt-death.png'),
    width: 64,
    height: 64,
  },
  'lucky/enemy-grunt-hurt.png': {
    source: require('../assets/themes/lucky/enemy-grunt-hurt.png'),
    width: 64,
    height: 64,
  },
  'lucky/enemy-grunt-idle.png': {
    source: require('../assets/themes/lucky/enemy-grunt-idle.png'),
    width: 64,
    height: 64,
  },
  'lucky/gear-necklace-t1.png': {
    source: require('../assets/themes/lucky/gear-necklace-t1.png'),
    width: 48,
    height: 48,
  },
  'lucky/gear-necklace-t2.png': {
    source: require('../assets/themes/lucky/gear-necklace-t2.png'),
    width: 48,
    height: 48,
  },
  'lucky/gear-necklace-t3.png': {
    source: require('../assets/themes/lucky/gear-necklace-t3.png'),
    width: 48,
    height: 48,
  },
  'lucky/gear-necklace-t4.png': {
    source: require('../assets/themes/lucky/gear-necklace-t4.png'),
    width: 48,
    height: 48,
  },
  'lucky/gear-ring1-t1.png': {
    source: require('../assets/themes/lucky/gear-ring1-t1.png'),
    width: 48,
    height: 48,
  },
  'lucky/gear-ring1-t2.png': {
    source: require('../assets/themes/lucky/gear-ring1-t2.png'),
    width: 48,
    height: 48,
  },
  'lucky/gear-ring1-t3.png': {
    source: require('../assets/themes/lucky/gear-ring1-t3.png'),
    width: 48,
    height: 48,
  },
  'lucky/gear-ring1-t4.png': {
    source: require('../assets/themes/lucky/gear-ring1-t4.png'),
    width: 48,
    height: 48,
  },
  'lucky/gear-ring2-t1.png': {
    source: require('../assets/themes/lucky/gear-ring2-t1.png'),
    width: 48,
    height: 48,
  },
  'lucky/gear-ring2-t2.png': {
    source: require('../assets/themes/lucky/gear-ring2-t2.png'),
    width: 48,
    height: 48,
  },
  'lucky/gear-ring2-t3.png': {
    source: require('../assets/themes/lucky/gear-ring2-t3.png'),
    width: 48,
    height: 48,
  },
  'lucky/gear-ring2-t4.png': {
    source: require('../assets/themes/lucky/gear-ring2-t4.png'),
    width: 48,
    height: 48,
  },
  'lucky/gear-weapon-t1.png': {
    source: require('../assets/themes/lucky/gear-weapon-t1.png'),
    width: 48,
    height: 48,
  },
  'lucky/gear-weapon-t2.png': {
    source: require('../assets/themes/lucky/gear-weapon-t2.png'),
    width: 48,
    height: 48,
  },
  'lucky/gear-weapon-t3.png': {
    source: require('../assets/themes/lucky/gear-weapon-t3.png'),
    width: 48,
    height: 48,
  },
  'lucky/gear-weapon-t4.png': {
    source: require('../assets/themes/lucky/gear-weapon-t4.png'),
    width: 48,
    height: 48,
  },
  'lucky/player-attack.png': {
    source: require('../assets/themes/lucky/player-attack.png'),
    width: 64,
    height: 64,
  },
  'lucky/player-hurt.png': {
    source: require('../assets/themes/lucky/player-hurt.png'),
    width: 64,
    height: 64,
  },
  'lucky/player-idle.png': {
    source: require('../assets/themes/lucky/player-idle.png'),
    width: 64,
    height: 64,
  },
  'lucky/shiny-cache.png': {
    source: require('../assets/themes/lucky/shiny-cache.png'),
    width: 48,
    height: 48,
  },
  'lucky/shiny-drop.png': {
    source: require('../assets/themes/lucky/shiny-drop.png'),
    width: 48,
    height: 48,
  },
  'lucky/shiny-frenzy.png': {
    source: require('../assets/themes/lucky/shiny-frenzy.png'),
    width: 48,
    height: 48,
  },
  'lucky/shiny-idle.png': {
    source: require('../assets/themes/lucky/shiny-idle.png'),
    width: 48,
    height: 48,
  },
  'lucky/spawn-popup.png': {
    source: require('../assets/themes/lucky/spawn-popup.png'),
    width: 96,
    height: 32,
  },
};
