// themeAssets.gen.ts — GENERATED by mobile/scripts/sync-theme-assets.mjs.
//
// Do not edit by hand: run `npm run mobile:assets` to regenerate. One literal
// `require()` per bundled theme PNG (Metro resolves static requires only), with
// the pixel size measured from each PNG's IHDR header. Keyed
// `<theme-name>/<file>` — the exact lookup `resolveAsset` performs.

import type { ImageSourcePropType } from 'react-native';

export interface ThemeAssetSource {
  /** The bundled image module Metro resolves from the literal require. */
  source: ImageSourcePropType;
  /** Pixel width measured from the PNG's IHDR header. */
  width: number;
  /** Pixel height measured from the PNG's IHDR header. */
  height: number;
}

export const THEME_ASSETS: Record<string, ThemeAssetSource> = {
  'fantasy/boss-grunt-attack-0.png': {
    source: require('../assets/themes/fantasy/boss-grunt-attack-0.png'),
    width: 96,
    height: 96,
  },
  'fantasy/boss-grunt-attack-1.png': {
    source: require('../assets/themes/fantasy/boss-grunt-attack-1.png'),
    width: 96,
    height: 96,
  },
  'fantasy/boss-grunt-death-0.png': {
    source: require('../assets/themes/fantasy/boss-grunt-death-0.png'),
    width: 96,
    height: 96,
  },
  'fantasy/boss-grunt-death-1.png': {
    source: require('../assets/themes/fantasy/boss-grunt-death-1.png'),
    width: 96,
    height: 96,
  },
  'fantasy/boss-grunt-death-2.png': {
    source: require('../assets/themes/fantasy/boss-grunt-death-2.png'),
    width: 96,
    height: 96,
  },
  'fantasy/boss-grunt-hurt-0.png': {
    source: require('../assets/themes/fantasy/boss-grunt-hurt-0.png'),
    width: 96,
    height: 96,
  },
  'fantasy/boss-grunt-hurt-1.png': {
    source: require('../assets/themes/fantasy/boss-grunt-hurt-1.png'),
    width: 96,
    height: 96,
  },
  'fantasy/boss-grunt-idle-0.png': {
    source: require('../assets/themes/fantasy/boss-grunt-idle-0.png'),
    width: 96,
    height: 96,
  },
  'fantasy/boss-grunt-idle-1.png': {
    source: require('../assets/themes/fantasy/boss-grunt-idle-1.png'),
    width: 96,
    height: 96,
  },
  'fantasy/enemy-grunt-attack-0.png': {
    source: require('../assets/themes/fantasy/enemy-grunt-attack-0.png'),
    width: 64,
    height: 64,
  },
  'fantasy/enemy-grunt-attack-1.png': {
    source: require('../assets/themes/fantasy/enemy-grunt-attack-1.png'),
    width: 64,
    height: 64,
  },
  'fantasy/enemy-grunt-death-0.png': {
    source: require('../assets/themes/fantasy/enemy-grunt-death-0.png'),
    width: 64,
    height: 64,
  },
  'fantasy/enemy-grunt-death-1.png': {
    source: require('../assets/themes/fantasy/enemy-grunt-death-1.png'),
    width: 64,
    height: 64,
  },
  'fantasy/enemy-grunt-death-2.png': {
    source: require('../assets/themes/fantasy/enemy-grunt-death-2.png'),
    width: 64,
    height: 64,
  },
  'fantasy/enemy-grunt-hurt-0.png': {
    source: require('../assets/themes/fantasy/enemy-grunt-hurt-0.png'),
    width: 64,
    height: 64,
  },
  'fantasy/enemy-grunt-hurt-1.png': {
    source: require('../assets/themes/fantasy/enemy-grunt-hurt-1.png'),
    width: 64,
    height: 64,
  },
  'fantasy/enemy-grunt-idle-0.png': {
    source: require('../assets/themes/fantasy/enemy-grunt-idle-0.png'),
    width: 64,
    height: 64,
  },
  'fantasy/enemy-grunt-idle-1.png': {
    source: require('../assets/themes/fantasy/enemy-grunt-idle-1.png'),
    width: 64,
    height: 64,
  },
  'fantasy/gear-necklace-t1-0.png': {
    source: require('../assets/themes/fantasy/gear-necklace-t1-0.png'),
    width: 48,
    height: 48,
  },
  'fantasy/gear-necklace-t2-0.png': {
    source: require('../assets/themes/fantasy/gear-necklace-t2-0.png'),
    width: 48,
    height: 48,
  },
  'fantasy/gear-necklace-t3-0.png': {
    source: require('../assets/themes/fantasy/gear-necklace-t3-0.png'),
    width: 48,
    height: 48,
  },
  'fantasy/gear-necklace-t4-0.png': {
    source: require('../assets/themes/fantasy/gear-necklace-t4-0.png'),
    width: 48,
    height: 48,
  },
  'fantasy/gear-ring1-t1-0.png': {
    source: require('../assets/themes/fantasy/gear-ring1-t1-0.png'),
    width: 48,
    height: 48,
  },
  'fantasy/gear-ring1-t2-0.png': {
    source: require('../assets/themes/fantasy/gear-ring1-t2-0.png'),
    width: 48,
    height: 48,
  },
  'fantasy/gear-ring1-t3-0.png': {
    source: require('../assets/themes/fantasy/gear-ring1-t3-0.png'),
    width: 48,
    height: 48,
  },
  'fantasy/gear-ring1-t4-0.png': {
    source: require('../assets/themes/fantasy/gear-ring1-t4-0.png'),
    width: 48,
    height: 48,
  },
  'fantasy/gear-ring2-t1-0.png': {
    source: require('../assets/themes/fantasy/gear-ring2-t1-0.png'),
    width: 48,
    height: 48,
  },
  'fantasy/gear-ring2-t2-0.png': {
    source: require('../assets/themes/fantasy/gear-ring2-t2-0.png'),
    width: 48,
    height: 48,
  },
  'fantasy/gear-ring2-t3-0.png': {
    source: require('../assets/themes/fantasy/gear-ring2-t3-0.png'),
    width: 48,
    height: 48,
  },
  'fantasy/gear-ring2-t4-0.png': {
    source: require('../assets/themes/fantasy/gear-ring2-t4-0.png'),
    width: 48,
    height: 48,
  },
  'fantasy/gear-weapon-t1-0.png': {
    source: require('../assets/themes/fantasy/gear-weapon-t1-0.png'),
    width: 48,
    height: 48,
  },
  'fantasy/gear-weapon-t2-0.png': {
    source: require('../assets/themes/fantasy/gear-weapon-t2-0.png'),
    width: 48,
    height: 48,
  },
  'fantasy/gear-weapon-t3-0.png': {
    source: require('../assets/themes/fantasy/gear-weapon-t3-0.png'),
    width: 48,
    height: 48,
  },
  'fantasy/gear-weapon-t4-0.png': {
    source: require('../assets/themes/fantasy/gear-weapon-t4-0.png'),
    width: 48,
    height: 48,
  },
  'fantasy/player-attack-0.png': {
    source: require('../assets/themes/fantasy/player-attack-0.png'),
    width: 64,
    height: 64,
  },
  'fantasy/player-attack-1.png': {
    source: require('../assets/themes/fantasy/player-attack-1.png'),
    width: 64,
    height: 64,
  },
  'fantasy/player-hurt-0.png': {
    source: require('../assets/themes/fantasy/player-hurt-0.png'),
    width: 64,
    height: 64,
  },
  'fantasy/player-hurt-1.png': {
    source: require('../assets/themes/fantasy/player-hurt-1.png'),
    width: 64,
    height: 64,
  },
  'fantasy/player-idle-0.png': {
    source: require('../assets/themes/fantasy/player-idle-0.png'),
    width: 64,
    height: 64,
  },
  'fantasy/player-idle-1.png': {
    source: require('../assets/themes/fantasy/player-idle-1.png'),
    width: 64,
    height: 64,
  },
  'fantasy/shiny-cache-0.png': {
    source: require('../assets/themes/fantasy/shiny-cache-0.png'),
    width: 48,
    height: 48,
  },
  'fantasy/shiny-cache-1.png': {
    source: require('../assets/themes/fantasy/shiny-cache-1.png'),
    width: 48,
    height: 48,
  },
  'fantasy/shiny-drop-0.png': {
    source: require('../assets/themes/fantasy/shiny-drop-0.png'),
    width: 48,
    height: 48,
  },
  'fantasy/shiny-drop-1.png': {
    source: require('../assets/themes/fantasy/shiny-drop-1.png'),
    width: 48,
    height: 48,
  },
  'fantasy/shiny-frenzy-0.png': {
    source: require('../assets/themes/fantasy/shiny-frenzy-0.png'),
    width: 48,
    height: 48,
  },
  'fantasy/shiny-frenzy-1.png': {
    source: require('../assets/themes/fantasy/shiny-frenzy-1.png'),
    width: 48,
    height: 48,
  },
  'fantasy/shiny-idle-0.png': {
    source: require('../assets/themes/fantasy/shiny-idle-0.png'),
    width: 48,
    height: 48,
  },
  'fantasy/shiny-idle-1.png': {
    source: require('../assets/themes/fantasy/shiny-idle-1.png'),
    width: 48,
    height: 48,
  },
  'fantasy/spawn-popup-0.png': {
    source: require('../assets/themes/fantasy/spawn-popup-0.png'),
    width: 96,
    height: 32,
  },
  'lucky/boss-grunt-attack-0.png': {
    source: require('../assets/themes/lucky/boss-grunt-attack-0.png'),
    width: 96,
    height: 96,
  },
  'lucky/boss-grunt-attack-1.png': {
    source: require('../assets/themes/lucky/boss-grunt-attack-1.png'),
    width: 96,
    height: 96,
  },
  'lucky/boss-grunt-death-0.png': {
    source: require('../assets/themes/lucky/boss-grunt-death-0.png'),
    width: 96,
    height: 96,
  },
  'lucky/boss-grunt-death-1.png': {
    source: require('../assets/themes/lucky/boss-grunt-death-1.png'),
    width: 96,
    height: 96,
  },
  'lucky/boss-grunt-death-2.png': {
    source: require('../assets/themes/lucky/boss-grunt-death-2.png'),
    width: 96,
    height: 96,
  },
  'lucky/boss-grunt-hurt-0.png': {
    source: require('../assets/themes/lucky/boss-grunt-hurt-0.png'),
    width: 96,
    height: 96,
  },
  'lucky/boss-grunt-hurt-1.png': {
    source: require('../assets/themes/lucky/boss-grunt-hurt-1.png'),
    width: 96,
    height: 96,
  },
  'lucky/boss-grunt-idle-0.png': {
    source: require('../assets/themes/lucky/boss-grunt-idle-0.png'),
    width: 96,
    height: 96,
  },
  'lucky/boss-grunt-idle-1.png': {
    source: require('../assets/themes/lucky/boss-grunt-idle-1.png'),
    width: 96,
    height: 96,
  },
  'lucky/enemy-grunt-attack-0.png': {
    source: require('../assets/themes/lucky/enemy-grunt-attack-0.png'),
    width: 64,
    height: 64,
  },
  'lucky/enemy-grunt-attack-1.png': {
    source: require('../assets/themes/lucky/enemy-grunt-attack-1.png'),
    width: 64,
    height: 64,
  },
  'lucky/enemy-grunt-death-0.png': {
    source: require('../assets/themes/lucky/enemy-grunt-death-0.png'),
    width: 64,
    height: 64,
  },
  'lucky/enemy-grunt-death-1.png': {
    source: require('../assets/themes/lucky/enemy-grunt-death-1.png'),
    width: 64,
    height: 64,
  },
  'lucky/enemy-grunt-death-2.png': {
    source: require('../assets/themes/lucky/enemy-grunt-death-2.png'),
    width: 64,
    height: 64,
  },
  'lucky/enemy-grunt-hurt-0.png': {
    source: require('../assets/themes/lucky/enemy-grunt-hurt-0.png'),
    width: 64,
    height: 64,
  },
  'lucky/enemy-grunt-hurt-1.png': {
    source: require('../assets/themes/lucky/enemy-grunt-hurt-1.png'),
    width: 64,
    height: 64,
  },
  'lucky/enemy-grunt-idle-0.png': {
    source: require('../assets/themes/lucky/enemy-grunt-idle-0.png'),
    width: 64,
    height: 64,
  },
  'lucky/enemy-grunt-idle-1.png': {
    source: require('../assets/themes/lucky/enemy-grunt-idle-1.png'),
    width: 64,
    height: 64,
  },
  'lucky/gear-necklace-t1-0.png': {
    source: require('../assets/themes/lucky/gear-necklace-t1-0.png'),
    width: 48,
    height: 48,
  },
  'lucky/gear-necklace-t2-0.png': {
    source: require('../assets/themes/lucky/gear-necklace-t2-0.png'),
    width: 48,
    height: 48,
  },
  'lucky/gear-necklace-t3-0.png': {
    source: require('../assets/themes/lucky/gear-necklace-t3-0.png'),
    width: 48,
    height: 48,
  },
  'lucky/gear-necklace-t4-0.png': {
    source: require('../assets/themes/lucky/gear-necklace-t4-0.png'),
    width: 48,
    height: 48,
  },
  'lucky/gear-ring1-t1-0.png': {
    source: require('../assets/themes/lucky/gear-ring1-t1-0.png'),
    width: 48,
    height: 48,
  },
  'lucky/gear-ring1-t2-0.png': {
    source: require('../assets/themes/lucky/gear-ring1-t2-0.png'),
    width: 48,
    height: 48,
  },
  'lucky/gear-ring1-t3-0.png': {
    source: require('../assets/themes/lucky/gear-ring1-t3-0.png'),
    width: 48,
    height: 48,
  },
  'lucky/gear-ring1-t4-0.png': {
    source: require('../assets/themes/lucky/gear-ring1-t4-0.png'),
    width: 48,
    height: 48,
  },
  'lucky/gear-ring2-t1-0.png': {
    source: require('../assets/themes/lucky/gear-ring2-t1-0.png'),
    width: 48,
    height: 48,
  },
  'lucky/gear-ring2-t2-0.png': {
    source: require('../assets/themes/lucky/gear-ring2-t2-0.png'),
    width: 48,
    height: 48,
  },
  'lucky/gear-ring2-t3-0.png': {
    source: require('../assets/themes/lucky/gear-ring2-t3-0.png'),
    width: 48,
    height: 48,
  },
  'lucky/gear-ring2-t4-0.png': {
    source: require('../assets/themes/lucky/gear-ring2-t4-0.png'),
    width: 48,
    height: 48,
  },
  'lucky/gear-weapon-t1-0.png': {
    source: require('../assets/themes/lucky/gear-weapon-t1-0.png'),
    width: 48,
    height: 48,
  },
  'lucky/gear-weapon-t2-0.png': {
    source: require('../assets/themes/lucky/gear-weapon-t2-0.png'),
    width: 48,
    height: 48,
  },
  'lucky/gear-weapon-t3-0.png': {
    source: require('../assets/themes/lucky/gear-weapon-t3-0.png'),
    width: 48,
    height: 48,
  },
  'lucky/gear-weapon-t4-0.png': {
    source: require('../assets/themes/lucky/gear-weapon-t4-0.png'),
    width: 48,
    height: 48,
  },
  'lucky/player-attack-0.png': {
    source: require('../assets/themes/lucky/player-attack-0.png'),
    width: 64,
    height: 64,
  },
  'lucky/player-attack-1.png': {
    source: require('../assets/themes/lucky/player-attack-1.png'),
    width: 64,
    height: 64,
  },
  'lucky/player-hurt-0.png': {
    source: require('../assets/themes/lucky/player-hurt-0.png'),
    width: 64,
    height: 64,
  },
  'lucky/player-hurt-1.png': {
    source: require('../assets/themes/lucky/player-hurt-1.png'),
    width: 64,
    height: 64,
  },
  'lucky/player-idle-0.png': {
    source: require('../assets/themes/lucky/player-idle-0.png'),
    width: 64,
    height: 64,
  },
  'lucky/player-idle-1.png': {
    source: require('../assets/themes/lucky/player-idle-1.png'),
    width: 64,
    height: 64,
  },
  'lucky/shiny-cache-0.png': {
    source: require('../assets/themes/lucky/shiny-cache-0.png'),
    width: 48,
    height: 48,
  },
  'lucky/shiny-cache-1.png': {
    source: require('../assets/themes/lucky/shiny-cache-1.png'),
    width: 48,
    height: 48,
  },
  'lucky/shiny-drop-0.png': {
    source: require('../assets/themes/lucky/shiny-drop-0.png'),
    width: 48,
    height: 48,
  },
  'lucky/shiny-drop-1.png': {
    source: require('../assets/themes/lucky/shiny-drop-1.png'),
    width: 48,
    height: 48,
  },
  'lucky/shiny-frenzy-0.png': {
    source: require('../assets/themes/lucky/shiny-frenzy-0.png'),
    width: 48,
    height: 48,
  },
  'lucky/shiny-frenzy-1.png': {
    source: require('../assets/themes/lucky/shiny-frenzy-1.png'),
    width: 48,
    height: 48,
  },
  'lucky/shiny-idle-0.png': {
    source: require('../assets/themes/lucky/shiny-idle-0.png'),
    width: 48,
    height: 48,
  },
  'lucky/shiny-idle-1.png': {
    source: require('../assets/themes/lucky/shiny-idle-1.png'),
    width: 48,
    height: 48,
  },
  'lucky/spawn-popup-0.png': {
    source: require('../assets/themes/lucky/spawn-popup-0.png'),
    width: 96,
    height: 32,
  },
};
